name: By Design
favicon: null
layout_spectrum: 0.3575994553975761
typography_spectrum: 0.49368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#050a0e'
    - '#34393d'
    - '#74777c'
    - '#a5a8ad'
  brandStrength: 1
  lightness: 0.16900592599995434
  saturation: 0.5
  rhythmicContrast: 0.46107777720317245
purpose: []
