name: By Design
favicon: null
layout_spectrum: 0.3575994553975761
typography_spectrum: 0.49368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c4145'
    - '#a68d67'
    - '#a7a9ac'
    - '#696152'
    - '#8b795d'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
