name: By Design
favicon: null
layout_spectrum: 0.3575994553975761
typography_spectrum: 0.27182333706878126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06782211689278483
  lightness: 0.16900592599995434
  saturation: 0.9930855825077742
  rhythmicContrast: 0.46107777720317245
purpose: []
